name = "ImageTrainer"
uuid = "c91a3fb0-2af8-11e9-219b-0536161190a2"
authors = ["Andrew McKay <andrew.s.mckay@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
